"""Seaborn-only plotting interface for redistribution-safe RL evidence tables."""

from __future__ import annotations

from collections.abc import Sequence

import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib.axes import Axes
from matplotlib.figure import Figure

from learning_atlas.core.artifacts import ArtifactStore
from learning_atlas.reporting.plots import publish_figure

Row = dict[str, str | float]


def _columns(rows: Sequence[Row], names: Sequence[str]) -> dict[str, list[str | float]]:
    if not rows:
        raise ValueError("cannot plot an empty evidence table")
    return {name: [row[name] for row in rows] for name in names}


def _line(
    ax: Axes,
    rows: Sequence[Row],
    x: str,
    y: str,
    *,
    title: str,
    xlabel: str,
    ylabel: str,
    hue: str = "method",
) -> None:
    if x in {"environment_steps", "interactions"}:
        # Seeds reach validation checkpoints at different interaction counts.
        # Connecting their interleaved means would invent one jagged trajectory.
        sns.lineplot(
            data=_columns(rows, (x, y, hue, "seed")),
            x=x,
            y=y,
            hue=hue,
            units="seed",
            estimator=None,
            alpha=0.75,
            ax=ax,
        )
    else:
        sns.lineplot(data=_columns(rows, (x, y, hue)), x=x, y=y, hue=hue, errorbar="sd", ax=ax)
    ax.set(title=title, xlabel=xlabel, ylabel=ylabel)


def publish_reinforcement_plots(
    tables: dict[str, list[Row]], store: ArtifactStore
) -> dict[str, str]:
    """Publish 20 deterministic diagnostics; shaded bands show seed SD, not a confidence claim.

    Input tables are generated by the validated experiment, not arbitrary files.
    Matplotlib supplies axes/layout/export only; every data mark is Seaborn.
    """

    paths: dict[str, str] = {}
    seeds = sorted({int(row["seed"]) for row in tables["test_returns"]})
    context = f"Offline CPU / synthetic environments | training seeds {seeds} | bands where present: seed SD"

    def save(name: str, figure: Figure) -> None:
        figure.text(0.01, 0.005, context, fontsize=8, color="0.3")
        figure.tight_layout(rect=(0, 0.035, 1, 1))
        paths[name] = publish_figure(figure, store, f"plots/{name}.png")

    with (
        sns.axes_style("whitegrid"),
        sns.plotting_context("notebook"),
        sns.color_palette("colorblind"),
    ):
        for distribution in ("bernoulli", "gaussian"):
            rows = [row for row in tables["bandits"] if row["distribution"] == distribution]
            figure, ax = plt.subplots(figsize=(9, 5))
            _line(
                ax,
                rows,
                "step",
                "regret",
                title=f"{distribution.title()} bandits: expected opportunity cost",
                xlabel="Interactions",
                ylabel="Cumulative pseudo-regret (reward units)",
            )
            ax.set_ylim(bottom=0)
            save(f"{distribution}_regret", figure)
        figure, axes = plt.subplots(1, 2, figsize=(12, 5))
        for ax, distribution in zip(axes, ("bernoulli", "gaussian"), strict=True):
            rows = [row for row in tables["bandits"] if row["distribution"] == distribution]
            _line(
                ax,
                rows,
                "step",
                "mean_reward",
                title=f"{distribution.title()} realized rewards",
                xlabel="Interactions",
                ylabel="Cumulative mean reward",
            )
        save("bandit_rewards", figure)
        figure, axes = plt.subplots(1, 2, figsize=(12, 5))
        for ax, distribution in zip(axes, ("bernoulli", "gaussian"), strict=True):
            rows = [row for row in tables["posteriors"] if row["distribution"] == distribution]
            long = [
                {"arm": row["arm"], "value": row[key], "statistic": key}
                for row in rows
                for key in ("mean", "truth", "posterior_sd")
            ]
            _line(
                ax,
                long,
                "arm",
                "value",
                hue="statistic",
                title=f"{distribution.title()} Thompson posterior",
                xlabel="Arm index",
                ylabel="Reward mean / posterior SD",
            )
        save("bandit_posteriors", figure)
        figure, ax = plt.subplots(figsize=(9, 5))
        # A zero residual is rendered at machine epsilon, with an explicit label.
        residuals = [
            {**row, "residual": max(float(row["residual"]), np.finfo(float).eps)}
            for row in tables["planning"]
        ]
        _line(
            ax,
            residuals,
            "iteration",
            "residual",
            title="Bellman convergence certificate (zeros at machine epsilon)",
            xlabel="Planner iteration",
            ylabel="Optimal Bellman residual (sup norm)",
        )
        ax.set_yscale("log")
        save("planning_residuals", figure)
        figure, ax = plt.subplots(figsize=(8, 5))
        grid = tables["grid_values"]
        matrix = np.full(
            (1 + int(max(row["row"] for row in grid)), 1 + int(max(row["column"] for row in grid))),
            np.nan,
        )
        labels = np.full(matrix.shape, "", dtype=object)
        arrows = ("↑", "→", "↓", "←")
        for row in grid:
            r, c = int(row["row"]), int(row["column"])
            matrix[r, c] = float(row["value"])
            labels[r, c] = f"{matrix[r, c]:.2f}\n{arrows[int(row['action'])]}"
        labels[-1, -1] = "0.00\nGoal"
        sns.heatmap(
            matrix,
            annot=labels,
            fmt="",
            mask=np.isnan(matrix),
            cmap="viridis",
            ax=ax,
            cbar_kws={"label": "Optimal discounted value"},
        )
        ax.set(
            title="Exact Gridworld value/policy: slip=0.1, gamma=0.95 (blank=wall)",
            xlabel="Column",
            ylabel="Row",
        )
        save("gridworld_policy", figure)
        for task in ("navigation", "cliff"):
            figure, ax = plt.subplots(figsize=(9, 5))
            rows = [row for row in tables["tabular"] if row["task"] == task]
            _line(
                ax,
                rows,
                "episode",
                "mean_return",
                title=f"{task.title()}: on-policy versus off-policy control",
                xlabel="Training episode (nonoverlapping ≤25-episode means)",
                ylabel="Training return (reward units)",
            )
            save(f"{task}_learning", figure)
        figure, ax = plt.subplots(figsize=(9, 5))
        rows = [row for row in tables["tabular"] if row["task"] == "cliff"]
        _line(
            ax,
            rows,
            "episode",
            "mean_cliff_falls",
            title="Cliff risk under continuing ε=0.1 exploration",
            xlabel="Training episode (nonoverlapping ≤25-episode means)",
            ylabel="Mean cliff falls per episode",
        )
        ax.set_ylim(bottom=0)
        save("cliff_risk", figure)
        figure, ax = plt.subplots(figsize=(9, 5))
        sns.barplot(
            data=_columns(tables["policy_gap"], ("task", "method", "start_value_gap")),
            x="task",
            y="start_value_gap",
            hue="method",
            errorbar="sd",
            ax=ax,
        )
        ax.set(
            title="Greedy learned-policy gap against exact dynamic programming",
            xlabel="Grid task",
            ylabel="Optimal minus learned start-state value",
        )
        save("tabular_policy_gap", figure)
        main = {"reinforce", "dqn", "ppo"}
        for table, title in (
            ("learning", "Neural control: training return"),
            ("validation", "Neural control: training-only validation checkpoints"),
        ):
            figure, ax = plt.subplots(figsize=(10, 5))
            rows = [row for row in tables[table] if row["method"] in main]
            _line(
                ax,
                rows,
                "episode",
                "mean_return",
                title=title,
                xlabel="Training episodes (budgets differ by method)",
                ylabel="CartPole return (steps survived)",
            )
            ax.set_ylim(bottom=0)
            save(f"neural_{table}", figure)
        seed_means: list[Row] = []
        for method in sorted({str(row["method"]) for row in tables["test_returns"]}):
            for seed in seeds:
                rewards = [
                    float(row["episode_return"])
                    for row in tables["test_returns"]
                    if row["method"] == method and row["seed"] == seed
                ]
                seed_means.append(
                    {"method": method, "seed": float(seed), "mean_return": float(np.mean(rewards))}
                )
        figure, ax = plt.subplots(figsize=(11, 5))
        sns.stripplot(
            data=_columns(seed_means, ("method", "mean_return", "seed")),
            x="method",
            y="mean_return",
            hue="seed",
            jitter=False,
            dodge=True,
            size=7,
            ax=ax,
        )
        ax.set(
            title="Untouched test: one point per independently trained policy",
            xlabel="Method / DQN sampling-target ablation",
            ylabel="Mean held-out return (steps survived)",
        )
        ax.tick_params(axis="x", rotation=20)
        ax.set_ylim(bottom=0)
        save("heldout_seed_means", figure)
        figure, ax = plt.subplots(figsize=(10, 5))
        rows = [row for row in tables["test_returns"] if row["method"] in main | {"random"}]
        sns.ecdfplot(
            data=_columns(rows, ("episode_return", "method")),
            x="episode_return",
            hue="method",
            ax=ax,
        )
        ax.set(
            title="Held-out return distribution (episodes clustered within trained policies)",
            xlabel="CartPole episode return",
            ylabel="Empirical cumulative fraction",
        )
        save("heldout_return_distribution", figure)
        figure, ax = plt.subplots(figsize=(10, 5))
        rows = [row for row in tables["validation"] if str(row["method"]).startswith("dqn")]
        _line(
            ax,
            rows,
            "episode",
            "mean_return",
            title="DQN ablations: same maximum budget; realized survival differs",
            xlabel="Training episodes",
            ylabel="Validation return (steps survived)",
        )
        save("dqn_ablation", figure)
        figure, ax = plt.subplots(figsize=(9, 5))
        rows = [
            {"baseline": key, "variance": row[key], "seed": row["seed"]}
            for row in tables["gradient_variance"]
            for key in ("without_baseline", "learned_baseline")
        ]
        sns.barplot(
            data=_columns(rows, ("baseline", "variance")),
            x="baseline",
            y="variance",
            errorbar="sd",
            ax=ax,
        )
        ax.set(
            title="REINFORCE: frozen-policy gradient variance on fresh trajectories",
            xlabel="Baseline (same trajectories paired)",
            ylabel="Trace of sample gradient covariance",
        )
        save("reinforce_gradient_variance", figure)
        figure, axes = plt.subplots(2, 3, figsize=(14, 8))
        rows = [row for row in tables["neural_diagnostics"] if row["method"] == "ppo"]
        for ax, metric in zip(
            axes.flat,
            (
                "approximate_kl",
                "clip_fraction",
                "entropy",
                "value_mse",
                "gradient_norm",
                "kl_early_stop",
            ),
            strict=True,
        ):
            _line(
                ax,
                rows,
                "environment_steps",
                metric,
                title=metric.replace("_", " ").title(),
                xlabel="Interactions",
                ylabel=metric.replace("_", " "),
            )
        figure.suptitle(
            "PPO optimization diagnostics: final accepted minibatch per rollout", y=1.02
        )
        save("ppo_optimization", figure)
        figure, ax = plt.subplots(figsize=(10, 5))
        rows = [
            row
            for row in tables["neural_diagnostics"]
            if str(row["method"]).startswith("dqn") and row["loss_observed"] == 1.0
        ]
        if rows:
            _line(
                ax,
                rows,
                "episode",
                "td_loss",
                title="DQN Huber TD loss (undefined pre-learning losses excluded)",
                xlabel="Training episode",
                ylabel="Mean minibatch Huber loss",
            )
        else:
            ax.text(
                0.5,
                0.5,
                "No optimizer updates in this reduced budget",
                ha="center",
                transform=ax.transAxes,
            )
            ax.set(
                title="DQN Huber TD loss: not observed", xlabel="Training episode", ylabel="Loss"
            )
        save("dqn_td_loss", figure)
        figure, ax = plt.subplots(figsize=(11, 5))
        sns.barplot(
            data=_columns(tables["resources"], ("method", "environment_steps")),
            x="method",
            y="environment_steps",
            errorbar="sd",
            ax=ax,
        )
        ax.set(
            title="Measured interaction cost (longer survival consumes more transitions)",
            xlabel="Method / ablation",
            ylabel="Environment transitions used",
        )
        ax.tick_params(axis="x", rotation=20)
        save("interaction_cost", figure)
        figure, ax = plt.subplots(figsize=(10, 5))
        counts = {
            (row["method"], row["seed"], row["episode"]): row["environment_steps"]
            for row in tables["neural_diagnostics"]
        }
        rows = [
            {**row, "interactions": counts[(row["method"], row["seed"], row["episode"])]}
            for row in tables["validation"]
            if row["method"] in main
        ]
        _line(
            ax,
            rows,
            "interactions",
            "mean_return",
            title="Validation return versus consumed interactions",
            xlabel="Measured environment interactions",
            ylabel="Validation return (steps survived)",
        )
        save("sample_efficiency", figure)
    return paths
